project:
  type: book
  output-dir: docs

execute:
  cache: true     # This enables caching for all chapters
  freeze: auto    # Recommended: only re-renders files that have changed

book:
  title: "Tidy Finance in Vietnam"
  author: "Mike"
  date: "2/1/2026"
  chapters:
    - index.qmd
    # - intro.qmd
    # - summary.qmd
    - 00_institutional_background.qmd
    - 01_working_with_stock_returns.qmd
    - 02_modern_portfolio_theory.qmd
    - 03_capm.qmd
    - 04_financial_statement_analysis.qmd
    - 05_discounted_cash_flow.qmd
    - 06_accessing_and_managing_financial_data.qmd
    - 07_datacore_data.qmd
    - 08_beta_estimation.qmd
    # - 09_univariate_portfolio_sort.qmd
    # - 10_size_sorts.qmd
    # - 11_value_bivariate.qmd
    - 12_fama_french.qmd
    - 13_fama_macbeth.qmd
    # can't have this until u collect more data for 06_accessing_and_managing_financial_data
    # - 14_factor_selection_ml.qmd
    - 20_conclusion.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt