project:
  type: book
  output-dir: docs

execute:
  cache: true     # This enables caching for all chapters
  freeze: auto    # Recommended: only re-renders files that have changed

book:
  title: "Applying Tidy Finance with Python to Vietnam"
  author: "Mike"
  date: "2/1/2026"
  site-url: "https://github.com/mikenguyen13/tidy_finance_vn"
  repo-url: "https://github.com/mikenguyen13/tidy_finance_vn"

  repo-branch: "main"
  # Adds "Edit this page" and "Report an issue" links (top-right area, depending on theme)
  repo-actions: [edit, issue]
   # Global top navigation
  # navbar:
  #   background: light
  #   pinned: true
  #   left:
  #     - text: "Home"
  #       href: index.qmd
  #     - text: "About"
  #       href: about.qmd
    # right:
    #   - icon: github
    #     href: "https://github.com/mikenguyen13/tidy_finance_vn"
    #   - text: "Privacy"
    #     href: privacy.qmd
    #   - text: "Cookies"
    #     href: cookies.qmd

  # Footer with dynamic year (works in HTML pages)
  page-footer:
    left: |
      <span id="copyright"></span> Mike. All rights reserved.
    # right:
    #   - text: "Privacy"
    #     href: privacy.qmd
    #   - text: "Cookies"
    #     href: cookies.qmd
    #   - text: "Source"
    #     href: "https://github.com/mikenguyen13/tidy_finance_vn"

  chapters:
    - index.qmd
    # - intro.qmd
    # - summary.qmd
    - 00_institutional_background.qmd
    - 01_working_with_stock_returns.qmd
    - 02_modern_portfolio_theory.qmd
    - 03_capm.qmd
    - 04_financial_statement_analysis.qmd
    - 05_discounted_cash_flow.qmd
    - 06_accessing_and_managing_financial_data.qmd
    - 07_datacore_data.qmd
    - 08_beta_estimation.qmd
    - 09_univariate_portfolio_sort.qmd
    # - 10_size_sorts.qmd
    # - 11_value_bivariate.qmd
    - 12_fama_french.qmd
    - 13_fama_macbeth.qmd
    # can't have this until u collect more data for 06_accessing_and_managing_financial_data
    # - 14_factor_selection_ml.qmd
    # - 15_exchange_rate.qmd
    - 16_institutional_ownership.qmd
    - 17_sue.qmd
    - 18_event_studies.qmd
    - 20_conclusion.qmd

    - references.qmd
  # appendices:
  #   - privacy.qmd

bibliography: references.bib

format:
  html:
    # theme:
    #   - cosmo
    #   - brand
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    code-tools: true

    # Site search box in navbar
    search: true

    footnotes-hover: true
    citations-hover: true

    # Social sharing preview cards
    open-graph: true
    twitter-card: true

    # Put your favicon in the repo root (or adjust the path)
    favicon: "favicon.ico"
    
    include-after-body:
      # - includes/cookie-consent.html
      - includes/year.js
      - includes/gtag-loader.html

  pdf:
    documentclass: scrreprt